### ISSUE TITLE
To-do's for the new version [Laravel 5.5 & Vuejs 2.1.10]

### ISSUE THREAD

**Issue by mikimaine** [mikimaine/ecommerce#26]
New version @TODO

- [ ] SPA using Vuejs

- [ ] Headless backend API for the e-commerce (No Blade)

- [ ]  Optimized product EAV datamodel (enable cache for each custome attribute)

- [ ] Horizon for Redies queues managment

- [ ] Redefine Use cases and modules

- [ ] New UI for both Frontend and Backend (finally moving to Bootstrap4, drop AdminLTE)

- [ ] Full Test coverage (TDD)

- [ ] Full Documentation
